---
title:  "[PID Jamovi]: Revisión progreso Lanzamiento"
date:   "2026-09-29"
format:
  docx:
    reference-doc: ../../www/minutes_styles.docx
gfm: default
---

**Horario:** 12:25 - 13:08 CEST

**Lugar:** Online: <https://teams.microsoft.com/meet/362761002209222?p=MNja9a0oz8mwVCRHYt>

**Asistentes:**

- Belén Fernández Castilla ([bfcastilla\@psi.uned.es](mailto:bfcastilla@psi.uned.es){.email}) \[BFC\]
- José Ángel Martínez Huertas ([jamartinez\@psi.uned.es](mailto:jamartinez@psi.uned.es){.email}) \[JMH\]
- Daniel Morillo ([dvmorillo\@psi.uned.es](mailto:dvmorillo@psi.uned.es){.email}) \[DMC\]
- Pilar Pozo Cabanillas ([ppozo\@psi.uned.es](mailto:ppozo@psi.uned.es){.email}) \[PPC\]
- Alejandro Martínez Mingo ([a.martinez.m\@psi.uned.es](mailto:a.martinez.m@psi.uned.es){.email}) \[AMM\]
- Celia Serrano Montilla ([cserrano\@psi.uned.es](mailto:cserrano@psi.uned.es){.email}) \[CSM\]

**Transcriptor:** DMC

# Puntos del orden del día

## Revisión y aprobación del acta del 2026-07-20

### Acuerdos

- **Aprobado**: Aprobar acta.

## Revisión de [Revisión de contenidos a evaluar](https://github.com/DaniMori/pid-iad-jamovi/issues/2)

### Debate

- Hoja con los contenidos idealmente "limpia" para tener la información estructurada ("machine-ready")

### Acuerdos

- **Aprobado**: Aprobar cierre de tarea (pasando listado de vídeos a nueva pestaña)

### Tareas

- **BFC**: Pasar listado de videos a nueva pestaña \[ASAP\]

## Revisión de [Diseño de los ítems de evaluación](https://github.com/DaniMori/pid-iad-jamovi/issues/1)

### Debate

- Variables "normales" no generan asimetría (difícil de simular)

### Acuerdos

- **Pospuesto**: Aprobar cierre de tarea

### Tareas

- **JMH**: Cambiar variable por "Salario_deseado" en ítem de asimetría \[ASAP\]

## Revisión de [Creación de módulos de actividad en Ágora](https://github.com/DaniMori/pid-iad-jamovi/issues/3)

### Debate

- Vídeo y subir vídeos

### Acuerdos

- **Aprobado**: Cambiar referencias a la tarea de "actividad voluntaria" a "PEC Jamovi"

- **Aprobado**: Usar formato PDF como archivo de subida de los resultados de Jamovi

- **Pospuesto**: Aprobar cierre de tarea

### Tareas

- **BFC**: Cambiar referencias a la tarea por "PEC Jamovi" \[ASAP\]

- **JMH**: Comprobar si se puede incluir ítem de "subir archivo" en la encuesta \[ASAP\]

- **JMH**: Crear ítem o módulo de actividad para "subir archivo" de resultados \[2026-10-09\]

- **JMH**: Pasar ítems de respuesta en la encuesta a formato "numérico" \[2026-10-09\]

- **JMH**: Añadir instrucciones de respuestas numéricas (dos decimales, punto como separador) a encuesta \[2026-10-09\]

## Revisión de [Elicitación de requisitos de la simulación](https://github.com/DaniMori/pid-iad-jamovi/issues/7)

### Debate

- Algunas relaciones entre variables son poco plausibles

### Acuerdos

- **Pospuesto**: Aprobar cierre de tarea

### Tareas

- **AMM**: Revisar y añadir restricciones a las correlaciones entre variables generadoras \[ASAP\]

## Revisión de [Implementación del código de la simulación](https://github.com/DaniMori/pid-iad-jamovi/issues/8)

### Debate

- La implementación del código actual es "hackeable"

### Acuerdos

- **Aprobado**: Pasar repositorio a "privado"

- **Aprobado**: Priorizar revisión (por CSM) de [Migración a Connect Cloud](https://github.com/DaniMori/pid-pec-iad/issues/19)

- **Pospuesto**: Aprobar cierre de tarea

### Tareas

- **BFC**: Hacer revisión de "caja negra" de la simulación \[2026-10-09\]

- **CSM**: Hacer revisión de "caja negra" de la simulación \[2026-10-09\]

- **DMC**: Actualizar restricciones de las correlaciones en el código \[2026-10-09\]

## Revisión de [Revisión y actualización de instrucciones](https://github.com/DaniMori/pid-iad-jamovi/issues/4)

### Debate

### Acuerdos

- **Aprobado**: Poner etiquetas y nombres de variables en las instrucciones

- **Rechazado**: Pedir respuestas numéricas exactamente como aparecen en Jamovi

- **Aprobado**: Pedir dos decimales y punto como separador decimal en respuestas numéricas

- **Pospuesto**: Aprobar cierre de tarea

### Tareas

- **JMH**: Cambiar referencias a la tarea por "PEC Jamovi" en instrucciones \[ASAP\]

- **JMH**: Añadir entrega de archivo de resultados en PDF a instrucciones \[ASAP\]

- **JMH**: Añadir instrucciones de respuestas numéricas (dos decimales, punto como separador) a instrucciones \[ASAP\]

## Revisión de [Migración a Connect Cloud](https://github.com/DaniMori/pid-pec-iad/issues/19)

### Debate

- Testeo de la app de descarga "condicionado" al cierre de esta tarea

### Acuerdos

- **Aprobado**: Priorizar testeo de la migración

- **Aprobado**: Posponer [revisión de instrucciones](https://github.com/DaniMori/pid-pec-iad/issues/34) al hito "fin del proyecto"

- **Pospuesto**: Aprobar cierre de tarea

### Tareas

- **CSM**: Revisar código de la migración \[2026-10-09\]

- **DMC**: Borrar rama desactualizada "update/dataset-simulator" \[ASAP\]

## Revisión de [Revisión y actualización de materiales auxiliares](https://github.com/DaniMori/pid-iad-jamovi/issues/5)

### Debate

- Vídeo de contenidos de Jamovi completo (por BFC)

### Tareas

- **JMH**: Hacer vídeo demostración de entrega de archivo de resultados de Jamovi \[ND\]

## Revisión de [Revisión y actualización del foro de ayuda](https://github.com/DaniMori/pid-iad-jamovi/issues/6)

### Debate

- Sin fecha de apertura, se hace visible cuando se activa la pestaña de Jamovi

### Tareas

- **BFC**: Revisar fecha de cierre y resto de configuración del foro de ayuda \[ND\]

## Revisión de [Implementación del código de corrección](https://github.com/DaniMori/pid-iad-jamovi/issues/40)

### Acuerdos

- **Aprobado**: Posponer inicio hasta aprobar el cierre de la simulación

# Próxima reunión

- **Objetivo**: Por determinar.

- **Fecha**: Por determinar.

- **Horario**: Por determinar.

# Adjuntos y enlaces

- [Acta del 2026-07-20](https://unedo365-my.sharepoint.com/:w:/r/personal/bfcastilla_psi_uned_es/Documents/2.%20Docencia/Comp_IAD/PIDs%20JAMOVI/PID%202026-27/Reuniones/2026-07-20.docx?d=w3b8748d1bf20464b9d1372bae07941aa&csf=1&web=1&e=VP362Z)

- [Planificación del hito "Lanzamiento"](https://github.com/users/DaniMori/projects/2/views/10)

# **Resumen de tareas:**

## AMM

- Revisar y añadir restricciones a las correlaciones entre variables generadoras \[ASAP\]

## BFC

- Pasar listado de videos a nueva pestaña \[ASAP\]

- Cambiar referencias a la tarea por "PEC Jamovi" \[ASAP\]

- Hacer revisión de "caja negra" de la simulación \[2026-10-09\]

- Revisar fecha de cierre y resto de configuración del foro de ayuda \[ND\]

## CSM

- Hacer revisión de "caja negra" de la simulación \[2026-10-09\]

- Revisar código de la migración \[2026-10-09\]

## DMC

- Borrar rama desactualizada "update/dataset-simulator" \[ASAP\]

- Actualizar restricciones de las correlaciones en el código \[2026-10-09\]

## JMH

- Cambiar variable por "Salario_deseado" en ítem de asimetría \[ASAP\]

- Comprobar si se puede incluir ítem de "subir archivo" en la encuesta \[ASAP\]

- Cambiar referencias a la tarea por "PEC Jamovi" en instrucciones \[ASAP\]

- Añadir entrega de archivo de resultados en PDF a instrucciones \[ASAP\]

- Añadir instrucciones de respuestas numéricas (dos decimales, punto como separador) a instrucciones \[ASAP\]

- Crear ítem o módulo de actividad para "subir archivo" de resultados \[2026-10-09\]

- Pasar ítems de respuesta en la encuesta a formato "numérico" \[2026-10-09\]

- Añadir instrucciones de respuestas numéricas (dos decimales, punto como separador) a encuesta \[2026-10-09\]

- Hacer vídeo demostración de entrega de archivo de resultados de Jamovi \[ND\]
