---
title:  "[PID Jamovi]: Revisión planificación Lanzamiento"
date:   "2026-07-20"
format:
  docx:
    reference-doc: ../../www/minutes_styles.docx
gfm: default
---

**Horario:** 13:00 - 13:30 CEST

**Lugar:** Online: <https://teams.microsoft.com/meet/39123835238646?p=3nyWKL5QQFRI5iqZI4>

**Asistentes:**

- Belén Fernández Castilla ([bfcastilla\@psi.uned.es](mailto:bfcastilla@psi.uned.es){.email}) \[BFC\]
- José Ángel Martínez Huertas ([jamartinez\@psi.uned.es](mailto:jamartinez@psi.uned.es){.email}) \[JMH\]
- Daniel Morillo ([dvmorillo\@psi.uned.es](mailto:dvmorillo@psi.uned.es){.email}) \[DMC\]
- Pilar Pozo Cabanillas ([ppozo\@psi.uned.es](mailto:ppozo@psi.uned.es){.email}) \[PPC\]
- Celia Serrano Montilla ([cserrano\@psi.uned.es](mailto:cserrano@psi.uned.es){.email}) \[CSM\]

**Excusados/as:**

- Alejandro Martínez Mingo ([a.martinez.m\@psi.uned.es](mailto:a.martinez.m@psi.uned.es){.email}) \[AMM\]

**Transcriptor:** DMC

# Puntos del orden del día

## Revisión y aprobación del acta del 2026-06-23

### Acuerdos

- **Aprobado**: Aprobar acta.

- **Pospuesto**: .

- **Rechazado**: .

## Revisión y aprobación de la planificación del hito "Lanzamiento"

### Debate

- Semana de pruebas presenciales: Afecta hasta "[Elicitación de requisitos de la simulación](https://github.com/DaniMori/pid-iad-jamovi/issues/7)"

- "[Creación de módulos de actividad en Ágora](https://github.com/DaniMori/pid-iad-jamovi/issues/3)" y "[Document "survey creation" instructions](https://github.com/DaniMori/pid-pec-iad/issues/8)" en paralelo (misma persona)

### Acuerdos

- **Aprobado**: Cambiar identificación de usuario por ID en lugar de email.

- **Pospuesto**: .

- **Rechazado**: .

### Tareas

- **DMC**: \[ASAP\]

- **BFC**: \[ND\]

- **ALL**: \[ND\]

- **JMH**: \[ND\]

- **ALL**: \[ND\]

- **DMC**: \[ND\]

- **AMM**, **CSM**: \[ND\]

- **DMC**: \[ND\]

# Sugerencias y preguntas

# Próxima reunión

- **Objetivo**: Por determinar.

- **Fecha**: Por determinar.

- **Horario**: Por determinar.

# **Resumen de tareas:**

## BFC

## JMH

## AMM

## DMC

## PPC

## CSM
