---
title:  "[PID Jamovi]: Revisión del backlog"
date:   "2026-06-23"
format:
  docx:
    reference-doc: ../../www/minutes_styles.docx
gfm: default
---

**Horario:** 15:30 GMT+2 - 16:30 GMT+2

**Lugar:** Sala 2.09 <https://teams.microsoft.com/meet/354653465339313?p=NKqTFdO60oS1lMtUpj>

**Asistentes:**

- Belén Fernández Castilla ([bfcastilla\@psi.uned.es](mailto:bfcastilla@psi.uned.es){.email}) \[BFC\]
- José Ángel Martínez Huertas ([jamartinez\@psi.uned.es](mailto:jamartinez@psi.uned.es){.email}) \[JMH\]
- Alejandro Martínez Mingo ([a.martinez.m\@psi.uned.es](mailto:a.martinez.m@psi.uned.es){.email}) \[AMM\]
- Daniel Morillo ([dvmorillo\@psi.uned.es](mailto:dvmorillo@psi.uned.es){.email}) \[DMC\]
- Pilar Pozo Cabanillas ([ppozo\@psi.uned.es](mailto:ppozo@psi.uned.es){.email}) \[PPC\]
- Celia Serrano Montilla ([cserrano\@psi.uned.es](mailto:cserrano@psi.uned.es){.email}) \[CSM\]

**Transcriptor:** DMC

# Puntos del orden del día

## Revisión y aprobación del acta del 2026-06-02

### Acuerdos

- **Aprobado**: Aprobar acta

## Revisión de hitos del proyecto

### Acuerdos

- **Aprobado**: Lanzamiento de la actividad: 2026-10-29

- **Aprobado**: Cierre de la actividad: 2027-01-22

- **Aprobado**: Cierre de calificaciones: 2027-02-23

## Asignación inicial de tareas en la propuesta del PID

### Debate

- Al contar para nota, podemos hacer más de 10 preguntas en la PEC

- Todos los procedimientos a realizar con Jamovi deben tener demostración en vídeos

- La actividad de tipo "encuesta" en Ágora puede responderse en más de una sesión

- Matriz de actividades debe incluir: ítems, análisis estadístico (contenido), materiales auxiliares, y temas

### Tareas

- **DMC**: Hacer planificación de tareas para el equipo \[ASAP\]

- **BFC**: Elaborar lista de contenidos a evaluar \[ND\]

- **ALL**: Revisar lista de contenidos a evaluar \[ND\]

- **JMH**: Elaborar matriz de actividades \[ND\]

- **ALL**: Revisar matriz de actividades \[ND\]

- **DMC**: Implementar código de simulación y corrección \[ND\]

- **AMM**, **CSM**: Revisar código de simulación y corrección \[ND\]

## Priorización y selección de tareas en el backlog

### Debate

- Se debate la eliminación de la dependencia del archivo CSV con los correos del profesorado para facilitar el uso del sistema por parte de terceros

### Acuerdos

- **Aprobado**: Prioizar tareas asignadas a hito "Lanzamiento".

- **Aprobado**: Eliminar la dependencia de los correos del profesorado en el código.

## Asignación de tareas en el backlog

### Debate

- Se requiere dominio de GitHub, {renv} y versiones de R (se utilizará R 4.6.0).

- Se acuerda documentar en un Notebook las instrucciones para la creación de encuestas en Ágora.

### Acuerdos

- **Aprobado**: BFC documentará la creación de encuestas en Ágora (incluyendo capturas de pantalla y configuración de campos numéricos).

### Tareas

- **DMC**: Hacer migración a Connect Cloud \[ND\]

- **BFC**: Documentar creación de encuestas en Ágora \[ND\]

- **DMC**, **AMM**, y **CSM**: Deslegar apps en Connect Cloud \[ND\]

## Gestión del PID y comunicación

### Debate

- Tener el repositorio de GitHub público puede dar problemas de seguridad.

### Acuerdos

- **Aprobado**: Usar Teams como canal principal de comunicación para el PID.

- **Aprobado**: Reestructurar el equipo de Teams en canal principal de IAD y un canal por PID.

- **Aprobado**: Centralizar documentación en subcarpeta "Documentación" en carpeta compartida de IAD.

- **Aprobado**: Mantener repositorio GitHub privado.

- **Rechazado**: Adoptar castellano para comunicaciones en GitHub.

- **Aprobado**: Traducir instrucciones y documentación de usuario al castellano.

### Tareas

- **DMC**: Reestructurar equipo de Teams \[ASAP\]

- **DMC**: Crear carpeta "Documentación" \[ASAP\]

# Próxima reunión

- **Objetivo**: Por determinar.

- **Fecha**: Por determinar.

- **Horario**: Por determinar.

# **Resumen de tareas:**

## BFC

- (con **PPC**) \[2026-09-30\]

- (con **JMH**) \[ASAP\]

## DMC

- \[ASAP\]

## JMH

- (con **BFC**) \[ASAP\]

## PPC

- (con **BFC**) \[2026-09-30\]

# **Resumen de tareas:**

## BFC

- \[ASAP\] Elaborar lista de contenidos evaluables.
- \[A lo largo del curso\] Documentar creación de encuestas en Ágora.

## DMC

- \[ASAP\] Ajustar calendario de hitos.
- \[ASAP\] Reestructurar equipo de Teams.
- \[ASAP\] Liderar migración a Connect Cloud.
