---
title:  "[PID Jamovi]: Revisión del backlog"
date:   "2026-06-23"
format:
  docx:
    reference-doc: ../../www/minutes_styles.docx
gfm: default
---

**Horario:** 15:30 GMT+2 - 16:30 GMT+2

**Lugar:** Online: <https://teams.microsoft.com/meet/354653465339313?p=NKqTFdO60oS1lMtUpj>

**Convocante:** Daniel Morillo Cuadrado [dvmorillo\@psi.uned.es](mailto:dvmorillo@psi.uned.es){.email} \[DMC\]

**Personas convocadas:**

- Belén Fernández Castilla [bfcastilla\@psi.uned.es](mailto:bfcastilla@psi.uned.es){.email} \[BFC\]
- José Ángel Martínez Huertas [jamartinez\@psi.uned.es](mailto:jamartinez@psi.uned.es){.email} \[JMH\]
- Alejandro Martínez Mingo ([a.martinez.m\@psi.uned.es](mailto:a.martinez.m@psi.uned.es){.email}) \[AMM\]
- Pilar Pozo Cabanillas ([ppozo\@psi.uned.es](mailto:ppozo@psi.uned.es){.email}) \[PPC\]
- Celia Serrano Montilla ([cserrano\@psi.uned.es](mailto:cserrano@psi.uned.es){.email}) \[CSM\]

# Preparación previa

- Revisar [acta del 2026-06-02](https://unedo365-my.sharepoint.com/:w:/r/personal/bfcastilla_psi_uned_es/Documents/2.%20Docencia/Comp_IAD/PIDs%20JAMOVI/PID%202026-27/Reuniones/2026-06-02.docx?d=w3ea05eb5e3b54e408439695b9a0e4b98&csf=1&web=1&e=XPN7WO)

- Revisar tareas propuestas para nuevo PID (pp. 9-10 y 13-14) en el [Anexo I a la solicitud del PID](https://unedo365-my.sharepoint.com/:b:/r/personal/bfcastilla_psi_uned_es/Documents/2.%20Docencia/Comp_IAD/PIDs%20JAMOVI/PID%202026-27/PID_2026-27_Jamovi_con_anexo.pdf?csf=1&web=1&e=zWWdI5)

- Revisar tareas propuestas para nuevo PID en [el "backlog"](https://github.com/users/DaniMori/projects/2/views/1)

# Orden del día

1.  Revisión y aprobación del acta del 2026-06-02 (5')

2.  Revisión de hitos del proyecto (5')

3.  Asignación inicial de tareas en la propuesta del PID (15')

4.  Priorización y selección de tareas en el backlog (15')

5.  Asignación de tareas en el backlog (10')

6.  Gestión del PID y comunicación (5')

7.  Sugerencias y preguntas (5')

# Adjuntos y enlaces

- [Acta del 2026-06-02](https://unedo365-my.sharepoint.com/:w:/r/personal/bfcastilla_psi_uned_es/Documents/2.%20Docencia/Comp_IAD/PIDs%20JAMOVI/PID%202026-27/Reuniones/2026-06-02.docx?d=w3ea05eb5e3b54e408439695b9a0e4b98&csf=1&web=1&e=XPN7WO)

- [Anexo I a la solicitud del PID](https://unedo365-my.sharepoint.com/:b:/r/personal/bfcastilla_psi_uned_es/Documents/2.%20Docencia/Comp_IAD/PIDs%20JAMOVI/PID%202026-27/PID_2026-27_Jamovi_con_anexo.pdf?csf=1&web=1&e=zWWdI5)

- [Backlog del proyecto](https://github.com/users/DaniMori/projects/2/views/1)
